Add namespace: {{ .Release.Namespace }} to all namespace scoped resources
kubewarden/helm-charts pull request #106
Opened 2022-06-15 13:56 UTC by floriankoch

2022-06-16 06:38 UTC, flavio commented
@kubewarden/kubewarden-developers seems easy and reasonable. Something we might pull of just in time for rc3?

2022-06-17 08:53 UTC, raulcabello commented on charts/kubewarden-controller/templates/webhooks.yaml
> +  namespace: {{ .Release.Namespace }}
we don't need this here since `MutatingWebhookConfiguration` is not a namespaced resource.

2022-06-17 08:55 UTC, raulcabello requested changes
Thanks @floriankoch ! Please have a look at the comment I left

2022-06-17 09:07 UTC, floriankoch commented
@raulcabello   fixed

2022-06-17 11:26 UTC, raulcabello approved these changes
LGTM, thanks!

2022-06-17 12:01 UTC, jvanz approved these changes

2022-06-17 12:03 UTC, merged