Release kubewarden-controller, kubewarden-defaults `1.3.0`
kubewarden/helm-charts pull request #178
Opened 2023-01-03 12:04 UTC by viccuad

## Description

- feat: `.Values.additionalLabels`, set default recommended labels, thanks to https://github.com/kubewarden/helm-charts/pull/176
- feat: `.Values.additionalAnnotations`
- fix: Bump controller image to `v1.4.1`: maintenance dependency bumps. The maintenance dependency bumps make the controller image pass with A image scans (even if vulnerabilities of the previous image were not affecting us).

Fix https://github.com/kubewarden/helm-charts/issues/177

## Test

## Additional Information

### Tradeoff

### Potential improvement

2023-01-03 15:29 UTC, viccuad commented
Tested it by deploying kubewarden-controller and kubewarden-defaults with the following values.yaml, and all fine, the resources have the correct labels and annotations:
```
---
# -- Additional labels to add to all resources
additionalLabels:
  app: kubewarden-defaults

# -- Additional annotations to add to all resources
additionalAnnotations:
  owner: IT-group1
```

2023-01-03 16:30 UTC, viccuad commented on charts/kubewarden-controller/templates/deployment.yaml
> +        {{- include "kubewarden-controller.annotations" . | nindent 8 }}
Maybe it's not useful to annotate to have this `Deployment spec.template.metadata.annotations`, that will get included in the Pods. Afterall, the pods are managed by the deployments and so.

2023-01-03 16:31 UTC, viccuad commented on charts/kubewarden-defaults/templates/policyserver-default.yaml
> +    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
same as https://github.com/kubewarden/helm-charts/pull/178/files#r1060752392 here.

2023-01-03 16:34 UTC, viccuad commented on charts/kubewarden-controller/templates/deployment.yaml
> +        {{- include "kubewarden-controller.annotations" . | nindent 8 }}
```suggestion
```
Removing this `Deployment spec.template.metadata.annotations`, that will get included in the Pods. Afterall, the pods are managed by the deployments and so.

2023-01-04 10:19 UTC, kravciak requested changes
Controller image bump to 1.4.1 works fine.

Labels do not work correctly, they are missing / present quite randomly on resources in kubewarden namespace

```bash
kubectl get -n kubewarden all -o name | xargs -L 1 -t kubectl get -n kubewarden -o json | jq '..|.annotations? //empty ,.labels? // empty'

# = pods
pods (controller & policyserver):
- have annotations
- no labels

# = services
services (controller):
- have annotations
- have labels

services (policyserver):
- no annotations
- no labels

# = deployments
deployments (kubewarden-controller):
- annotation on metadata and templates
- labels on metadata only

deployments (policy-server):
- annotations on templates only
- no labels on metadata or templates

# = replicasets
replicaset (controller):
- annotations on metadata and templates
- no labels

replicaset (policyserver):
- annotations on templates only
- no labels
```

2023-01-04 10:32 UTC, viccuad commented on charts/kubewarden-controller/templates/deployment.yaml
> +        {{- include "kubewarden-controller.annotations" . | nindent 8 }}
removed in https://github.com/kubewarden/helm-charts/pull/178/commits/1a2faf835462d99e0f225c1a51c160357933d731, use the already present `Values.podAnnotations` for controller

2023-01-04 10:32 UTC, viccuad commented on charts/kubewarden-defaults/templates/policyserver-default.yaml
> +    {{- include "kubewarden-defaults.annotations" . | nindent 4 }}
removed in https://github.com/kubewarden/helm-charts/pull/178/commits/1a2faf835462d99e0f225c1a51c160357933d731, use the already present `Values.policyServer.annotations` for policy server

2023-01-04 11:17 UTC, viccuad commented
Ok, I have changed it to the following:

```
kubectl get -n kubewarden all -o name | xargs -L 1 -t kubectl get -n kubewarden -o json | jq '..|.annotations? //empty ,.labels? // empty'

# = pods
pods (controller & policyserver):
- have annotations: set up with values already existing, apart from this PR. See
    `Values.podAnnotations` for controller
    `Values.policyServer.annotations` for policy server
- have labels: name & instance only (selector labels)

# = services
services (controller):
- have annotations
- have labels

services (policyserver):
the policy-servers services are created and managed by the controller, hence, no annotations and labels.
It would be good to add the recommended labels though.

# = deployments
deployments (kubewarden-controller):
- annotation on metadata and templates
- labels on metadata only
I think both of these are correct. The deployment spec contains PodTemplateSpec, which can't have labels for example.

deployments (policy-server):
The policy-server deployments are created and managed by the controller, hence, no annotations and labels.
It would be good to add the recommended labels though.

# = replicasets
replicaset (controller):
- annotations on metadata and templates
- selector labels

replicaset (policyserver):
Since the deployment is created and managed by the controller, it needs to be solved there.
```

The most important part is that we have the recommended labels for Helm-managed resources (we have from what I see), and that those can also be custom annotated (we can from what I see).

2023-01-04 14:53 UTC, viccuad commented
After review from kravciak, changed it to all labels (including those defined via `.Values.additionalLabels`) are set in the controller Deployment.

Tested it locally by deploying the charts with `additionalLabels` and `additionalAnnotations` set.

2023-01-04 14:57 UTC, kravciak approved these changes

2023-01-04 14:57 UTC, merged