Prevent Policy Server Crash in case of a maintenance in Kubernetes Nodepools
kubewarden/helm-charts pull request #383
Opened 2024-02-07 13:11 UTC by ferhatguneri

## Description

If policy server crash because of wrong clusteradmissionpolicy it is blocking pod to be created and cannot evaluate resources correctly. which is affecting control plane. therefore need to keep policy-server always available.

2024-02-07 15:31 UTC, flavio commented
Thanks for the contribution. This fixes only the `PolicyServer` named `default`. The proper fix should be done inside of the kubewarden-controller.
This is tracked with https://github.com/kubewarden/kubewarden-controller/issues/564

2024-02-07 15:34 UTC, ferhatguneri commented
Hi @flavio , Should I add this change to the kubewarden-controller?

2024-02-07 15:41 UTC, flavio commented
Yes, that would be great. Take a look at https://github.com/kubewarden/kubewarden-controller/issues/564#issuecomment-1781175791 and implement the "Pod Disruption Budget" section.

Feel free to reach out if something is not clear or if you need help

2024-02-07 15:41 UTC, ferhatguneri commented
Hi @flavio I'm aware of that issue but there is no progress since long time. This is a very critical problem and I believe it needs to be fixed immediately. Do you have any idea how long it will take to get it fixed? It is not really good idea to patch these helm charts internally and deal with the upcoming changes.

2024-02-07 15:43 UTC, flavio commented
I think we can start working on this fix during the next sprint and make it part of the 1.11 release, but I have to discuss that with the other maintainers.

2024-02-08 09:31 UTC, viccuad requested changes
Hi, many thanks for bringing this forward!

I totally agree with providing a PodDisruptionBudget, yet we have the policy for the default values to not be production ready; people deploy with the defaults to test in a local cluster, and there's a myriad of production deployment flavours that cannot be covered via the default values.

I would welcome an optional configurable setting for the PodDisruptionBudget and the minimum replicaCount.

2024-02-09 14:30 UTC, closed without merging

2024-02-09 14:30 UTC, flavio commented
Closing, we will fix that inside of the controller with https://github.com/kubewarden/kubewarden-controller/issues/564