feat: PodDisruptionBudget configuration
kubewarden/helm-charts pull request #414
Opened 2024-03-27 19:04 UTC by jvanz

## Description

This update introduces new settings for managing the PolicyServer's Pod Disruption Budget, along with necessary permissions for operating the controller. We've also implemented a JSON schema for basic validation of these new settings. Please note, you cannot use both settings simultaneously; only one can be set at a time.

Fix https://github.com/kubewarden/kubewarden-controller/issues/692

2024-04-02 10:21 UTC, fabriziosestito approved these changes

2024-04-04 10:20 UTC, flavio requested changes

2024-04-04 11:50 UTC, jvanz commented on charts/kubewarden-controller/templates/rbac.yaml
> +  - watch
Yes, I've change the controller PR and forgot to update the files here. It's done now

2024-04-05 12:31 UTC, viccuad approved these changes

2024-04-08 10:00 UTC, flavio approved these changes

2024-04-08 10:42 UTC, merged