Revert the default policy server finalizer in use
kubewarden/helm-charts pull request #468
Opened 2024-06-17 14:19 UTC by jvanz

## Description

This reverts commit e514fa7c65c45f3d631544e15c6a55208169a765. This is necessary because the controller using the same finalizer is not released yet.

2024-06-17 15:06 UTC, kravciak approved these changes

2024-06-17 15:06 UTC, viccuad commented
Note , this is a duplicate of https://github.com/kubewarden/helm-charts/pull/467 xD. I'm ok with this one, closing the other.

2024-06-17 15:06 UTC, viccuad approved these changes

2024-06-17 15:06 UTC, viccuad requested changes

2024-06-17 15:06 UTC, viccuad commented on charts/kubewarden-defaults/Chart.yaml
> +version: 2.0.3
we need a bump in `catalog.cattle.io/upstream-version, too.

2024-06-17 17:31 UTC, jvanz commented
> Note , this is a duplicate of #467 xD. I'm ok with this one, closing the other.

Sorry, I've missed your PR. Closing this one.

2024-06-17 17:42 UTC, jvanz commented
@viccuad I've tried to update  your PR (using force push) to change a commit message and did a mess in the branch. Losing the commit with the fix. I'm sorry. I've fixed your comment in this PR and I'll merge it.

2024-06-17 17:46 UTC, merged

2024-06-18 06:55 UTC, viccuad commented
@jvanz no problem! I'm glad that is out!