Bump kubewarden-controller chart to v0.3.6.
kubewarden/helm-charts pull request #56
Opened 2022-01-31 18:04 UTC by jvanz

2022-02-01 08:59 UTC, viccuad requested changes
I think we need to bump the crd files from kubewarden-controller too.

2022-02-01 09:03 UTC, viccuad approved these changes

2022-02-01 12:51 UTC, ereslibre approved these changes

2022-02-03 15:04 UTC, jvanz commented
Just to document. This PR is waiting for this [change](https://github.com/kubewarden/docs/pull/82)

2022-02-03 16:19 UTC, merged