Add missing policyServer configuration values.
kubewarden/helm-charts pull request #85
Opened 2022-05-06 20:41 UTC by jvanz

Adds the values `imagePullSecret`, `insecureSources` and `sourceAuthorities`
allowing the users to configure the policy server configuration with the
same name.

Fix #84

2022-05-10 08:47 UTC, flavio approved these changes
I haven't tried it, but it looks good to me

2022-05-10 08:47 UTC, flavio commented on charts/kubewarden-defaults/README.md
> +| `policyServer.imagePullSecret`           | Name of ImagePullSecret secret in the same namespace, used for pulling policies from repositories.                       | ``                  |
I hope the suggestion won't mess up the backticks...

```suggestion
| `policyServer.imagePullSecret` | Name of ImagePullSecret secret in the same namespace, used both for pulling the container images and the policies from OCI repositories. | `` |
```

2022-05-10 08:48 UTC, flavio requested changes
I just realized you didn't bump the chart versions. Please do that as part of this PR

2022-05-10 11:52 UTC, jvanz commented
This is an example of the yaml files generated:

values.yml:

```yaml
# Policy Server settings
policyServer:
  replicaCount: 1
  image:
    repository: ghcr.io/kubewarden/policy-server
    tag: "v0.2.7"
  serviceAccountName: policy-server
  # verificationConfig: your_configmap
    # Configmap containing a Sigstore verification configuration under a key
    # named `verification-config`. Must be on the same ns as the PolicyServer.
  permissions:
    # All permissions are cluster-wide. Even namespaced resources are
    # granted access in all namespaces at this time.
    - apiGroup: ""
      resources:
        - namespaces
        - services
    - apiGroup: "networking.k8s.io"
      resources:
        - ingresses
  telemetry:
    enabled: True
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
  annotations: {}
  # imagePullSecret stores the secret name used to pull images from repositories.
  # The secret should be in the same namespace of the Policy Server
  #
  # Example of usage:
  imagePullSecret: "mysecret"

  # insecureSources store a list of allowed insecure restrigies.
  #
  # Example of usage:
  insecureSources:
    - "source1"
    - "source2"

  # sourceAuthorities is a list of the URIs and their PEM encoded certificates
  # used to authenticate them
  #
  # Example of usage:
  sourceAuthorities:
    - uri: "uri1"
      certs:
        - "cert1"
        - "cert2"
    - uri: "uri2"
      certs:
        - "cert3"
    - uri: "uri3"
      certs:
        - "cert4"

```

The `helm template` command output 

```yaml
# Source: kubewarden-defaults/templates/policyserver-default.yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: default
  finalizers:
    - kubewarden
spec:
  image: ghcr.io/kubewarden/policy-server:v0.2.7
  serviceAccountName: policy-server
  replicas: 1
  annotations:
      "sidecar.opentelemetry.io/inject": "true"
  env:
    - name: KUBEWARDEN_ENABLE_METRICS
      value: "1"
    - name: KUBEWARDEN_LOG_FMT
      value: otlp
    - name: "KUBEWARDEN_LOG_LEVEL"
      value: "info"
  imagePullSecret: "mysecret"
  insecureSources:
    - "source1"
    - "source2"
  sourceAuthorities:
    uri1:
      - "cert1"
      - "cert2"
    uri2:
      - "cert3"
    uri3:
      - "cert4"

```

2022-05-10 12:16 UTC, jvanz commented
After installing the Helm chart. I can see this in the cluster:

```
$ k8s get configmap policy-server-default -o yaml                                                                                           
apiVersion: v1
data:
  policies.yml: '{}'
  sources.yml: '{"insecure_sources":["source1","source2"],"source_authorities":{"uri1":[{"type":"Data","data":"cert1"},{"type":"Data","data":"cert2"}],"uri2":[{"type":"Data","data":"cert3"}],"uri3":[{"type":"Data","data":"cert4"}]}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-10T12:10:53Z"
  labels:
    kubewarden/policy-server: default
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:policies.yml: {}
        f:sources.yml: {}
      f:metadata:
        f:labels:
          .: {}
          f:kubewarden/policy-server: {}
    manager: manager
    operation: Update
    time: "2022-05-10T12:10:53Z"
  name: policy-server-default
  namespace: default
  resourceVersion: "1546"
  uid: cc617df3-85a6-4055-9e66-eb492df55a48
```

The default policy server pod:

```
$ k8s get pods policy-server-default-84896bc77b-6gnn2 -o json | jq ".spec.volumes"
[
  {
    "emptyDir": {},
    "name": "policy-store"
  },
  {
    "name": "certs",
    "secret": {
      "defaultMode": 420,
      "secretName": "policy-server-default"
    }
  },
  {
    "configMap": {
      "defaultMode": 420,
      "items": [
        {
          "key": "policies.yml",
          "path": "policies.yml"
        }
      ],
      "name": "policy-server-default"
    },
    "name": "policies"
  },
  {
    "name": "imagepullsecret",
    "secret": {
      "defaultMode": 420,
      "secretName": "mysecret"
    }
  },
  {
    "configMap": {
      "defaultMode": 420,
      "name": "policy-server-default"
    },
    "name": "sources"
  },
  {
    "name": "kube-api-access-rgrhx",
    "projected": {
      "defaultMode": 420,
      "sources": [
        {
          "serviceAccountToken": {
            "expirationSeconds": 3607,
            "path": "token"
          }
        },
        {
          "configMap": {
            "items": [
              {
                "key": "ca.crt",
                "path": "ca.crt"
              }
            ],
            "name": "kube-root-ca.crt"
          }
        },
        {
          "downwardAPI": {
            "items": [
              {
                "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "metadata.namespace"
                },
                "path": "namespace"
              }
            ]
          }
        }
      ]
    }
  }
]

```

2022-05-13 09:34 UTC, viccuad requested changes
LGTM, but I released `kubewarden-defaults-0.1.2` yesterday, so the chart version needs another bump, sorry :pensive: .

One silly question, aren't we always generating the template with `imagePullSecret`, `insecureSources`, `sourceAuthorities` present, but empty? couldn't that bring us problems?

2022-05-17 13:33 UTC, jvanz commented
> LGTM, but I released `kubewarden-defaults-0.1.2` yesterday, so the chart version needs another bump, sorry pensive .

No problems. ;)

> One silly question, aren't we always generating the template with `imagePullSecret`, `insecureSources`, `sourceAuthorities` present, but empty? couldn't that bring us problems?

@viccuad, this change only add the fields if some value is defined. In the yaml template, I've added a `if` statement to check if the values are defined. Empty values make the if statement to return false. Take a look in this example with the default values file:

```yaml
# This file was autogenerated.

# Common settings across multiple charts. These settings will be used
# by more than one chart and they ideally need to match during the
# installation of the charts consuming this values.
common:
  policyServer:
    default:
      name: default
      enabled: true

# Policy Server settings
policyServer:
  replicaCount: 1
  image:
    repository: ghcr.io/kubewarden/policy-server
    tag: "v0.2.7"
  serviceAccountName: policy-server
  # verificationConfig: your_configmap
    # Configmap containing a Sigstore verification configuration under a key
    # named `verification-config`. Must be on the same ns as the PolicyServer.
  permissions:
    # All permissions are cluster-wide. Even namespaced resources are
    # granted access in all namespaces at this time.
    - apiGroup: ""
      resources:
        - namespaces
        - services
    - apiGroup: "networking.k8s.io"
      resources:
        - ingresses
  telemetry:
    enabled: True
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
  annotations: {}
  # imagePullSecret stores the secret name used to pull images from repositories.
  # The secret should be in the same namespace of the Policy Server
  #
  # Example of usage:
  # imagePullSecret: "mysecret"
  imagePullSecret:

  # insecureSources store a list of allowed insecure restrigies.
  #
  # Example of usage:
  #insecureSources:
  #  - "source1"
  #  - "source2"
  insecureSources:

  # sourceAuthorities is a list of the URIs and their PEM encoded certificates
  # used to authenticate them
  #
  # Example of usage:
  # sourceAuthorities:
  #   - uri: "uri1"
  #     certs:
  #       - "cert1"
  #       - "cert2"
  #   - uri: "uri2"
  #     certs:
  #       - "cert3"
  #   - uri: "uri3"
  #     certs:
  #       - "cert4"
  sourceAuthorities:

recommendedPolicies:
  enabled: False
  skipNamespaces:
    - calico-system
    - cattle-alerting
    - cattle-fleet-local-system
    - cattle-fleet-system
    - cattle-global-data
    - cattle-global-nt
    - cattle-impersonation-system
    - cattle-istio
    - cattle-logging
    - cattle-pipeline
    - cattle-prometheus
    - cattle-system
    - cert-manager
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - rancher-operator-system
    - security-scan
    - tigera-operator
  defaultPolicyMode: "monitor"
  allowPrivilegeEscalationPolicy:
    module: "ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11"
    name: "no-privilege-escalation"
  hostNamespacePolicy:
    module: "ghcr.io/kubewarden/policies/host-namespaces-psp:v0.1.2"
    name: "no-host-namespace-sharing"
  podPrivilegedPolicy:
    module: "ghcr.io/kubewarden/policies/pod-privileged:v0.1.10"
    name: "no-privileged-pod"
  userGroupPolicy:
    module: "ghcr.io/kubewarden/policies/user-group-psp:v0.2.0"
    name: "do-not-run-as-root"
```

```console
---
# Source: kubewarden-defaults/templates/policy-server-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-server
  namespace: default
---
# Source: kubewarden-defaults/templates/policy-server-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewarden-context-watcher
rules:
- apiGroups:
  - ""
  resources: ["namespaces","services"]
  verbs:
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources: ["ingresses"]
  verbs:
  - list
  - watch
---
# Source: kubewarden-defaults/templates/policy-server-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewarden-context-watcher
subjects:
- kind: ServiceAccount
  name: policy-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubewarden-context-watcher
  apiGroup: rbac.authorization.k8s.io
---
# Source: kubewarden-defaults/templates/policyserver-default.yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: default
  finalizers:
    - kubewarden
spec:
  image: ghcr.io/kubewarden/policy-server:v0.2.7
  serviceAccountName: policy-server
  replicas: 1
  annotations:
      "sidecar.opentelemetry.io/inject": "true"
  env:
    - name: KUBEWARDEN_ENABLE_METRICS
      value: "1"
    - name: KUBEWARDEN_LOG_FMT
      value: otlp
    - name: "KUBEWARDEN_LOG_LEVEL"
      value: "info"
```

So, I think we are safe. ;)

2022-05-18 09:33 UTC, raulcabello approved these changes
LGTM, thanks!

2022-05-18 11:13 UTC, jvanz commented
It seems that we are not facing the issue mentioned by @viccuad  in comment https://github.com/kubewarden/helm-charts/pull/85#pullrequestreview-971960106 and we have some approves. Therefore, I'm merging this. @viccuad if you find something else, let me know. I'll fix asap!  Thanks

2022-05-18 11:14 UTC, merged